import React from 'react';
import { screen, act } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { renderWithRouter } from './helpers/renderWithRouter';
import App from '../App';

describe('Testando o componente Recipes Details', () => {
  test('Verificando o meals ', async () => {
    // renderWithRouter(<App />);
    const { history } = renderWithRouter(<App />);
    act(() => { history.push('/meals/52977'); });
    const emailInput = screen.getByTestId('email-input');
    const passwordInput = screen.getByTestId('password-input');
    const subimtButton = screen.getByTestId('login-submit-btn');
    userEvent.type(emailInput, 'email@teste.com');
    userEvent.type(passwordInput, '123456');
    userEvent.click(subimtButton);
    expect(emailInput).toBeInTheDocument();
    expect(passwordInput).toBeInTheDocument();
    expect(subimtButton).toBeInTheDocument();
    const meals = screen.getByRole('heading', { name: /meals/i });
    const btnBeef = screen.getByTestId('Beef-category-filter');
    const btnBreakfast = screen.getByTestId('Breakfast-category-filter');
    const btnChicken = screen.getByTestId('Chicken-category-filter');
    const btnDessert = screen.getByTestId('Dessert-category-filter');
    const btnGoat = screen.getByTestId('Goat-category-filter');
    const btnAll = screen.getByTestId('All-category-filter');
    expect(meals).toBeInTheDocument();
    userEvent.click(btnBeef);
    userEvent.click(btnBreakfast);
    userEvent.click(btnChicken);
    userEvent.click(btnDessert);
    userEvent.click(btnGoat);
    userEvent.click(btnAll);
    const detalhesFotos = screen.getByRole('img', { name: /foto-de-comida/i });
    expect(detalhesFotos).toBeInTheDocument();
    const detalhe1 = await screen.findByText(/lentils1 cup/i);
    const detalhe2 = screen.getByText(/onion1 large/i);
    const detalhe3 = screen.getByText(/carrots1 large/i);
    const detalhe4 = screen.getByText(/tomato puree1 tbs/i);
    const detalhe5 = screen.getByText(/cumin2 tsp/i);
    const detalhe6 = screen.getByText(/paprika1 tsp/i);
    const detalhe7 = screen.getByText(/mint1\/2 tsp/i);
    const detalhe8 = screen.getByText(/thyme1\/2 tsp/i);
    const detalhe9 = screen.getByText(/black pepper1\/4 tsp/i);
    const detalhe10 = screen.getByText(/red pepper flakes1\/4 tsp/i);
    const detalhe11 = screen.getByText(/vegetable stock4 cups/i);
    const detalhe12 = screen.getByText(/water1 cup/i);
    const detalhe13 = screen.getByText(/sea saltpinch/i);
    expect(detalhe1).toBeInTheDocument();
    expect(detalhe2).toBeInTheDocument();
    expect(detalhe3).toBeInTheDocument();
    expect(detalhe4).toBeInTheDocument();
    expect(detalhe5).toBeInTheDocument();
    expect(detalhe6).toBeInTheDocument();
    expect(detalhe7).toBeInTheDocument();
    expect(detalhe8).toBeInTheDocument();
    expect(detalhe9).toBeInTheDocument();
    expect(detalhe10).toBeInTheDocument();
    expect(detalhe11).toBeInTheDocument();
    expect(detalhe12).toBeInTheDocument();
    expect(detalhe13).toBeInTheDocument();
  });
  test('Verificando o drink ', async () => {
    // renderWithRouter(<App />);
    const { history } = renderWithRouter(<App />);
    act(() => { history.push('/drinks/15997'); });
    const emailInput = screen.getByTestId('email-input');
    const passwordInput = screen.getByTestId('password-input');
    const subimtButton = screen.getByTestId('login-submit-btn');
    userEvent.type(emailInput, 'email@teste.com');
    userEvent.type(passwordInput, '123456');
    userEvent.click(subimtButton);
    expect(emailInput).toBeInTheDocument();
    expect(passwordInput).toBeInTheDocument();
    expect(subimtButton).toBeInTheDocument();
    const drinks = screen.getByRole('heading', { name: /drinks/i });
    const drinkCategory = screen.getByTestId('Ordinary Drink-category-filter');
    const cocktailCategory = screen.getByTestId('Cocktail-category-filter');
    const shakeCategory = screen.getByTestId('Shake-category-filter');
    const categoryFilter = screen.getByTestId('Other/Unknown-category-filter');
    const cocoaCategory = screen.getByTestId('Cocoa-category-filter');
    const btnAll = screen.getByTestId('All-category-filter');
    expect(drinks).toBeInTheDocument();
    userEvent.click(drinkCategory);
    userEvent.click(cocktailCategory);
    userEvent.click(shakeCategory);
    userEvent.click(categoryFilter);
    userEvent.click(cocoaCategory);
    userEvent.click(btnAll);
    const detalhesFotos = screen.getByRole('img', { name: /recipe-photo/i });
    expect(detalhesFotos).toBeInTheDocument();
    const detalhe1 = await screen.findByText(/Gin/i);
    const detalhe2 = screen.getByText(/Light rum/i);
    const detalhe3 = screen.getByText(/Tequila/i);
    const detalhe4 = screen.getByText(/Triple Sec/i);
    const detalhe5 = screen.getByText(/Vodka/i);
    const detalhe6 = screen.getByText(/Coca-Cola/i);
    const detalhe7 = screen.getByText(/Sweet and sour/i);
    const detalhe8 = screen.getByText(/Bitters/i);
    const detalhe9 = screen.getByText(/Lemon/i);
    const detalhe10 = screen.getByText(/oz/i);
    expect(detalhe1).toBeInTheDocument();
    expect(detalhe2).toBeInTheDocument();
    expect(detalhe3).toBeInTheDocument();
    expect(detalhe4).toBeInTheDocument();
    expect(detalhe5).toBeInTheDocument();
    expect(detalhe6).toBeInTheDocument();
    expect(detalhe7).toBeInTheDocument();
    expect(detalhe8).toBeInTheDocument();
    expect(detalhe9).toBeInTheDocument();
    expect(detalhe10).toBeInTheDocument();
  });
});
